version: '3'
services:
  web:
    build: ./backend
    command: sh -c "python manage.py migrate && gunicorn localbox.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./media:/app/media
    env_file: .env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    command: npm run start
    env_file: .env
    volumes:
      - ./media:/app/media
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
